/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "IN_1.h"
#include "IN_Clock.h"
#include "IN_2.h"
#include "IN_3.h"
#include "IN_1_Out.h"
#include "IN_1_Out_aliases.h"
#include "IN_2_Out.h"
#include "IN_2_Out_aliases.h"
#include "IN_3_Out.h"
#include "IN_3_Out_aliases.h"
#include "EN_PIN.h"
#include "EN_PIN_aliases.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Clock_1.h"
#include "Timer.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_rx_wake.h"
#include "UART_rx_wake_aliases.h"
#include "UART_RX_WAKEUP_IRQ.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

