# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\bonfi\Downloads\PSoC Creator\ReactionWheel\ReactionWheel.cydsn\ReactionWheel.cyprj
# Date: Fri, 03 Apr 2026 23:54:26 GMT
#set_units -time ns
create_clock -name {IN_Clock(FFB)} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/ff_div_11}] [get_pins {ClockBlock/ff_div_12}] [get_pins {ClockBlock/ff_div_15}]]
create_clock -name {I2C_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {UART_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {IN_Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 2 3} [list]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 7 13} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]


# Component constraints for C:\Users\bonfi\Downloads\PSoC Creator\ReactionWheel\ReactionWheel.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\bonfi\Downloads\PSoC Creator\ReactionWheel\ReactionWheel.cydsn\ReactionWheel.cyprj
# Date: Fri, 03 Apr 2026 23:54:22 GMT
